ALTER TABLE "RetentionControl" DROP CONSTRAINT "RetentionControl_kind_check";
ALTER TABLE "RetentionControl" ADD CONSTRAINT "RetentionControl_kind_check" CHECK (
  kind IN ('REPORT','HOLD','MODERATION_POST','MODERATION_COMMENT','MODERATION_TOPIC','APPEAL',
    'ACCOUNT_STATE','AUTHOR_WITHDRAW_POST','AUTHOR_WITHDRAW_COMMENT','TOPIC_ACCESS',
    'POST_DISCOVERY','DISCOVERY_PREFERENCES','NOTIFICATION_PREFERENCES','AUTHOR_BELL',
    'ADMIN_SUPPORT','ADMIN_REPORT','ADMIN_CLAIM'));
ALTER TABLE "RetentionControl" DROP CONSTRAINT "RetentionControl_account_scope";
ALTER TABLE "RetentionControl" ADD CONSTRAINT "RetentionControl_account_scope" CHECK (
  (kind='ACCOUNT_STATE' AND target::text='ACCOUNT' AND "sourceId"="targetId")
  OR (kind IN ('TOPIC_ACCESS','POST_DISCOVERY','DISCOVERY_PREFERENCES','NOTIFICATION_PREFERENCES','AUTHOR_BELL','ADMIN_SUPPORT','ADMIN_REPORT','ADMIN_CLAIM') AND target::text='ACCOUNT')
  OR (kind NOT IN ('ACCOUNT_STATE','TOPIC_ACCESS','POST_DISCOVERY','DISCOVERY_PREFERENCES','NOTIFICATION_PREFERENCES','AUTHOR_BELL','ADMIN_SUPPORT','ADMIN_REPORT','ADMIN_CLAIM') AND target::text<>'ACCOUNT'));
