CREATE TABLE "CalendarLayerPreference" (
  "id" TEXT NOT NULL,
  "ownerId" TEXT NOT NULL,
  "calendarId" TEXT NOT NULL,
  "followed" BOOLEAN NOT NULL DEFAULT true,
  "visible" BOOLEAN NOT NULL DEFAULT true,
  "color" TEXT NOT NULL DEFAULT 'DEFAULT',
  "version" INTEGER NOT NULL DEFAULT 1,
  "recoveryRequired" BOOLEAN NOT NULL DEFAULT false,
  "requestKey" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "CalendarLayerPreference_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "CalendarLayerPreference_bounds" CHECK (version > 0 AND color IN ('DEFAULT','BLUE','GREEN','PURPLE','ORANGE','ROSE') AND ("requestKey" IS NULL OR length("requestKey") BETWEEN 1 AND 120) AND (NOT "recoveryRequired" OR (NOT followed AND NOT visible)))
);
CREATE UNIQUE INDEX "CalendarLayerPreference_ownerId_calendarId_key" ON "CalendarLayerPreference"("ownerId", "calendarId");
CREATE INDEX "CalendarLayerPreference_calendarId_idx" ON "CalendarLayerPreference"("calendarId");
ALTER TABLE "CalendarLayerPreference" ADD CONSTRAINT "CalendarLayerPreference_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "PlatformUser"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CalendarLayerPreference" ADD CONSTRAINT "CalendarLayerPreference_calendarId_fkey" FOREIGN KEY ("calendarId") REFERENCES "PlatformCalendar"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Missing preferences preserve existing overlays. Explicit unfollows are retained.
-- Extend the protected recovery journal without altering earlier controls.
ALTER TABLE "RetentionControl" DROP CONSTRAINT "RetentionControl_kind_check";
ALTER TABLE "RetentionControl" ADD CONSTRAINT "RetentionControl_kind_check" CHECK (
 kind IN ('REPORT','HOLD','MODERATION_POST','MODERATION_COMMENT','MODERATION_GROUP','MODERATION_TOPIC','MODERATION_EXCHANGE',
 'GROUP_ACCESS','TOPIC_ACCESS','POST_DISCOVERY','EXCHANGE_VISIBILITY','EXCHANGE_FAVORITE','EXCHANGE_SAVED_SEARCH','EXCHANGE_NEED','PANTRY_HUB','EXCHANGE_INQUIRY','EXCHANGE_CONTACT','EXCHANGE_DEFAULTS','DISCOVERY_PREFERENCES','CALENDAR_LAYER','FOLLOWING_LISTS','NOTIFICATION_PREFERENCES',
 'AUTHOR_BELL','ADMIN_SUPPORT','ADMIN_REPORT','ADMIN_CLAIM','APPEAL','ACCOUNT_STATE',
 'AUTHOR_WITHDRAW_POST','AUTHOR_WITHDRAW_COMMENT','SUPPORT_MESSAGE','SUPPORT_ATTACHMENT','FEEDBACK_PROMPT',
 'FEEDBACK_CHOICES','FEEDBACK_IDEA','FEEDBACK_SUBSCRIPTION','FEEDBACK_REVIEW','PHOTO_TAG','PHOTO_TAG_PREFERENCES','PROFILE_LOCATION','PROFILE_MODULES','VOLUNTEER_OPPORTUNITY','VOLUNTEER_APPLICATION'));
ALTER TABLE "RetentionControl" DROP CONSTRAINT "RetentionControl_account_scope";
ALTER TABLE "RetentionControl" ADD CONSTRAINT "RetentionControl_account_scope" CHECK (
 (kind IN ('ACCOUNT_STATE','FEEDBACK_PROMPT') AND target::text='ACCOUNT' AND "sourceId"="targetId")
 OR (kind IN ('GROUP_ACCESS','TOPIC_ACCESS','POST_DISCOVERY','EXCHANGE_VISIBILITY','EXCHANGE_FAVORITE','EXCHANGE_SAVED_SEARCH','EXCHANGE_NEED','PANTRY_HUB','EXCHANGE_INQUIRY','EXCHANGE_CONTACT','EXCHANGE_DEFAULTS','DISCOVERY_PREFERENCES','CALENDAR_LAYER','FOLLOWING_LISTS','NOTIFICATION_PREFERENCES','AUTHOR_BELL','ADMIN_SUPPORT','ADMIN_REPORT','ADMIN_CLAIM','FEEDBACK_CHOICES','FEEDBACK_IDEA','FEEDBACK_SUBSCRIPTION','FEEDBACK_REVIEW','PHOTO_TAG','PHOTO_TAG_PREFERENCES','PROFILE_LOCATION','PROFILE_MODULES','VOLUNTEER_OPPORTUNITY','VOLUNTEER_APPLICATION') AND target::text='ACCOUNT')
 OR (kind NOT IN ('ACCOUNT_STATE','FEEDBACK_PROMPT','GROUP_ACCESS','TOPIC_ACCESS','POST_DISCOVERY','EXCHANGE_VISIBILITY','EXCHANGE_FAVORITE','EXCHANGE_SAVED_SEARCH','EXCHANGE_NEED','PANTRY_HUB','EXCHANGE_INQUIRY','EXCHANGE_CONTACT','EXCHANGE_DEFAULTS','DISCOVERY_PREFERENCES','CALENDAR_LAYER','FOLLOWING_LISTS','NOTIFICATION_PREFERENCES','AUTHOR_BELL','ADMIN_SUPPORT','ADMIN_REPORT','ADMIN_CLAIM','FEEDBACK_CHOICES','FEEDBACK_IDEA','FEEDBACK_SUBSCRIPTION','FEEDBACK_REVIEW','PHOTO_TAG','PHOTO_TAG_PREFERENCES','PROFILE_LOCATION','PROFILE_MODULES','VOLUNTEER_OPPORTUNITY','VOLUNTEER_APPLICATION') AND target::text<>'ACCOUNT'));
