-- Existing location disclosure remains unchanged until its owner edits it.
ALTER TABLE "PlatformUser"
 ADD COLUMN "dateFormat" TEXT NOT NULL DEFAULT 'DEFAULT',
 ADD COLUMN "timeFormat" TEXT NOT NULL DEFAULT 'DEFAULT',
 ADD COLUMN "regionalVersion" INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN "locationAudience" TEXT NOT NULL DEFAULT 'MEMBERS',
 ADD COLUMN "locationVersion" INTEGER NOT NULL DEFAULT 0,
 ADD COLUMN "locationRecoveryRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "PlatformUser" ADD CONSTRAINT "PlatformUser_regional_format_check" CHECK (
 "dateFormat" IN ('DEFAULT','MDY','DMY','YMD') AND "timeFormat" IN ('DEFAULT','H12','H24') AND "regionalVersion" >= 0);
ALTER TABLE "PlatformUser" ADD CONSTRAINT "PlatformUser_location_audience_check" CHECK (
 "locationAudience" IN ('ONLY_ME','MEMBERS') AND "locationVersion" >= 0
 AND (NOT "locationRecoveryRequired" OR ("locationAudience"='ONLY_ME' AND location IS NULL)));
ALTER TABLE "RetentionControl" DROP CONSTRAINT "RetentionControl_kind_check";
ALTER TABLE "RetentionControl" ADD CONSTRAINT "RetentionControl_kind_check" CHECK (
 kind IN ('REPORT','HOLD','MODERATION_POST','MODERATION_COMMENT','MODERATION_TOPIC',
 'TOPIC_ACCESS','POST_DISCOVERY','DISCOVERY_PREFERENCES','NOTIFICATION_PREFERENCES',
 'AUTHOR_BELL','ADMIN_SUPPORT','ADMIN_REPORT','ADMIN_CLAIM','APPEAL','ACCOUNT_STATE',
 'AUTHOR_WITHDRAW_POST','AUTHOR_WITHDRAW_COMMENT','SUPPORT_MESSAGE','SUPPORT_ATTACHMENT','FEEDBACK_PROMPT',
 'FEEDBACK_CHOICES','FEEDBACK_IDEA','FEEDBACK_SUBSCRIPTION','FEEDBACK_REVIEW','PHOTO_TAG','PHOTO_TAG_PREFERENCES','PROFILE_LOCATION'));
ALTER TABLE "RetentionControl" DROP CONSTRAINT "RetentionControl_account_scope";
ALTER TABLE "RetentionControl" ADD CONSTRAINT "RetentionControl_account_scope" CHECK (
 (kind IN ('ACCOUNT_STATE','FEEDBACK_PROMPT') AND target::text='ACCOUNT' AND "sourceId"="targetId")
 OR (kind IN ('TOPIC_ACCESS','POST_DISCOVERY','DISCOVERY_PREFERENCES','NOTIFICATION_PREFERENCES','AUTHOR_BELL','ADMIN_SUPPORT','ADMIN_REPORT','ADMIN_CLAIM','FEEDBACK_CHOICES','FEEDBACK_IDEA','FEEDBACK_SUBSCRIPTION','FEEDBACK_REVIEW','PHOTO_TAG','PHOTO_TAG_PREFERENCES','PROFILE_LOCATION') AND target::text='ACCOUNT')
 OR (kind NOT IN ('ACCOUNT_STATE','FEEDBACK_PROMPT','TOPIC_ACCESS','POST_DISCOVERY','DISCOVERY_PREFERENCES','NOTIFICATION_PREFERENCES','AUTHOR_BELL','ADMIN_SUPPORT','ADMIN_REPORT','ADMIN_CLAIM','FEEDBACK_CHOICES','FEEDBACK_IDEA','FEEDBACK_SUBSCRIPTION','FEEDBACK_REVIEW','PHOTO_TAG','PHOTO_TAG_PREFERENCES','PROFILE_LOCATION') AND target::text<>'ACCOUNT'));
ALTER TABLE "RetentionControl" ADD CONSTRAINT "RetentionControl_profile_location_scope" CHECK (
 kind <> 'PROFILE_LOCATION' OR ("sourceId"="targetId" AND payload->>'operatorId'="targetId"));
